const data = [
  {
    id: 1,
    car: "Mitsubishi",
    car_model: "Montero",
    imgSrc:
      "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/00q2/267323/2001-mitsubishi-montero-road-test-review-car-and-driver-photo-9589-s-original.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
    car_color: "Yellow",
    car_model_year: 2002,
    car_vin: "SAJWJ0FF3F8321657",
    price: "$2814.46",
    availability: false,
    type: "large",
    popularity: 4.3,
  },
  {
    id: 2,
    car: "Volkswagen",
    car_model: "Passat",
    imgSrc:
      "https://assets.volkswagen.com/is/image/volkswagenag/new_cars-passat_estate-gallery4-1_1-2500x2500?Zml0PWNyb3AlMkMxJndpZD04MDAmaGVpPTgwMCZmbXQ9anBlZyZxbHQ9NzkmYmZjPW9mZiYxMjM4",
    car_color: "Maroon",
    car_model_year: 2008,
    car_vin: "WBANV9C51AC203320",
    price: "$1731.98",
    availability: false,
    type: "small",
    popularity: 3.9,
  },
  {
    id: 3,
    car: "Saturn",
    car_model: "L-Series",
    car_color: "Red",
    car_model_year: 2003,
    car_vin: "1HGCR6F34EA246317",
    price: "$2238.35",
    availability: true,
    imgSrc:
      "https://consumerguide.com/wp-content/uploads/2014/07/00130021990001.jpg",
    type: "small",
    popularity: 4.9,
  },
  {
    id: 4,
    car: "Jeep",
    car_model: "Compass",
    car_color: "Violet",
    car_model_year: 2012,
    car_vin: "4USBT33454L511606",
    price: "$2732.99",
    availability: false,
    imgSrc:
      "https://rentingplus.com/wp-content/uploads/2022/10/Jeep-Compass-Limited_White.jpg",
    type: "large",
    popularity: 4.2,
  },
  {
    id: 5,
    car: "Mitsubishi",
    car_model: "Lancer Evolution",
    car_color: "Purple",
    car_model_year: 2002,
    car_vin: "WAU2GBFCXDN339713",
    price: "$3849.47",
    availability: false,
    imgSrc:
      "https://baycitymitsubishi.co.nz/wp-content/uploads/2021/03/2017-Mitsubishi-Lancer-NGR159-1.jpg.webp",
    type: "small",
    popularity: 5,
  },
  {
    id: 6,
    car: "Chevrolet",
    car_model: "Suburban",
    car_color: "Indigo",
    car_model_year: 2009,
    car_vin: "WAUSH98E96A592763",
    price: "$1252.30",
    availability: false,
    imgSrc:
      "https://queautocompro.com/wp-content/uploads/2019/10/2012-suburban-1024x800.jpg",
    type: "large",
    popularity: 4.6,
  },
  {
    id: 7,
    car: "Dodge",
    car_model: "Ram Van B350",
    car_color: "Yellow",
    car_model_year: 1994,
    car_vin: "KNADH4A37A6919967",
    price: "$1762.42",
    availability: true,
    imgSrc:
      "https://d323w7klwy72q3.cloudfront.net/i/a/2014/20141104govt/hires/H9089.JPG",
    type: "large",
    popularity: 4.7,
  },
  {
    id: 8,
    car: "Isuzu",
    car_model: "Ascender",
    car_color: "Teal",
    car_model_year: 2004,
    car_vin: "5GTMNGEE8A8713093",
    price: "$1081.40",
    availability: true,
    imgSrc:
      "https://www.edmunds.com/assets/m/for-sale/94-4nuet16s746701217/img-1-600x400.jpg",
    type: "large",
    popularity: 3.6,
  },
  {
    id: 9,
    car: "BMW",
    car_model: "6 Series",
    car_color: "Purple",
    car_model_year: 2008,
    car_vin: "5TDBY5G16DS675822",
    price: "$1258.99",
    availability: true,
    imgSrc:
      "https://imgd.aeplcdn.com/1200x900/n/cw/ec/56639/bmw-6-series-gt-left-rear-three-quarter0.jpeg?wm=0",
    type: "small",
    popularity: 4.2,
  },
  {
    id: 10,
    car: "Mitsubishi",
    car_model: "GTO",
    car_color: "Purple",
    car_model_year: 1994,
    car_vin: "JM1NC2PFXE0140518",
    price: "$3822.92",
    availability: false,
    imgSrc:
      "https://japanesenostalgiccar.com/wordpress/wp-content/uploads/2015/10/1990-Mitsubishi-3000GT.jpg",
    type: "small",
    popularity: 4.5,
  },

  {
    id: 11,
    car: "Mazda",
    car_model: "5",
    car_color: "Red",
    car_model_year: 2010,
    car_vin: "WAUNE78P18A342660",
    price: "$3963.20",
    availability: true,
    imgSrc:
      "https://media.ed.edmunds-media.com/mazda/5/2012/oem/2012_mazda_5_passenger-minivan_grand-touring_fq_oem_1_1600.jpg",
    type: "small",
    popularity: 4.2,
  },
  {
    id: 12,
    car: "Audi",
    car_model: "Q7",
    car_color: "Pink",
    car_model_year: 2012,
    car_vin: "WA1WYBFE2AD448505",
    price: "$1144.27",
    availability: true,
    imgSrc:
      "https://www.motortrend.com/uploads/2022/09/2023-Audi-Q7-front-three-quarter-view-42.jpg",
    type: "large",
    popularity: 4.7,
  },
  {
    id: 13,
    car: "Mercedes-Benz",
    car_model: "SL-Class",
    car_color: "Aquamarine",
    car_model_year: 1989,
    car_vin: "4A4AP3AU8FE713946",
    price: "$1386.49",
    availability: true,
    imgSrc:
      "https://media.ed.edmunds-media.com/mercedes-benz/sl-class/2019/oem/2019_mercedes-benz_sl-class_convertible_sl-450_fq_oem_1_1600.jpg",
    type: "small",
    popularity: 4.9,
  },
  {
    id: 14,
    car: "Volvo",
    car_model: "C70",
    car_color: "Red",
    car_model_year: 2012,
    car_vin: "WAUHGBFC9DN768366",
    price: "$1366.96",
    availability: true,
    imgSrc:
      "https://i.gaw.to/content/photos/08/48/084826_Volvo_C70_Inscription_Toute_noire_ou_toute_blanche.jpg",
    type: "small",
    popularity: 3.9,
  },
  //   {
  //     id: 15,
  //     car: "GMC",
  //     car_model: "Envoy XL",
  //     car_color: "Green",
  //     car_model_year: 2006,
  //     car_vin: "WA1AV74L67D649365",
  //     price: "$1221.46",
  //     availability: false,

  //   },
  //   {
  //     id: 16,
  //     car: "GMC",
  //     car_model: "Vandura G3500",
  //     car_color: "Teal",
  //     car_model_year: 1996,
  //     car_vin: "1FMJK2A5XAE576485",
  //     price: "$1877.63",
  //     availability: true,
  //   },
  //   {
  //     id: 17,
  //     car: "Cadillac",
  //     car_model: "CTS",
  //     car_color: "Pink",
  //     car_model_year: 2003,
  //     car_vin: "WAUVC68E02A369838",
  //     price: "$2646.55",
  //     availability: true,
  //   },
  //   {
  //     id: 18,
  //     car: "BMW",
  //     car_model: "X5 M",
  //     car_color: "Mauv",
  //     car_model_year: 2012,
  //     car_vin: "WA1YD54B63N613712",
  //     price: "$2076.03",
  //     availability: true,
  //   },
  //   {
  //     id: 19,
  //     car: "Dodge",
  //     car_model: "Viper",
  //     car_color: "Turquoise",
  //     car_model_year: 1999,
  //     car_vin: "WAUMF98P66A420495",
  //     price: "$1323.48",
  //     availability: true,
  //   },
  //   {
  //     id: 20,
  //     car: "Ford",
  //     car_model: "Taurus",
  //     car_color: "Mauv",
  //     car_model_year: 2002,
  //     car_vin: "WAUUL58E15A338821",
  //     price: "$1801.89",
  //     availability: false,
  //   },
  //   {
  //     id: 21,
  //     car: "Suzuki",
  //     car_model: "Swift",
  //     car_color: "Green",
  //     car_model_year: 1996,
  //     car_vin: "WAUDH98E78A844182",
  //     price: "$2716.12",
  //     availability: true,
  //   },
  //   {
  //     id: 22,
  //     car: "Chrysler",
  //     car_model: "Town & Country",
  //     car_color: "Mauv",
  //     car_model_year: 2010,
  //     car_vin: "5XXGM4A71CG888959",
  //     price: "$3480.31",
  //     availability: false,
  //   },
  //   {
  //     id: 23,
  //     car: "Maserati",
  //     car_model: "430",
  //     car_color: "Blue",
  //     car_model_year: 1991,
  //     car_vin: "2FMPK3J94FB631826",
  //     price: "$1660.01",
  //     availability: false,
  //   },
  //   {
  //     id: 24,
  //     car: "Toyota",
  //     car_model: "Tacoma Xtra",
  //     car_color: "Puce",
  //     car_model_year: 1996,
  //     car_vin: "5TDDCRFH8FS931829",
  //     price: "$3532.17",
  //     availability: false,
  //   },
  //   {
  //     id: 25,
  //     car: "Volkswagen",
  //     car_model: "Eurovan",
  //     car_color: "Pink",
  //     car_model_year: 2000,
  //     car_vin: "WAUUL78E45A616915",
  //     price: "$1645.81",
  //     availability: true,
  //   },
  //   {
  //     id: 26,
  //     car: "Ford",
  //     car_model: "Econoline E150",
  //     car_color: "Puce",
  //     car_model_year: 2002,
  //     car_vin: "5N1AN0NU9BC466461",
  //     price: "$3464.94",
  //     availability: true,
  //   },
  //   {
  //     id: 27,
  //     car: "GMC",
  //     car_model: "Sierra Denali",
  //     car_color: "Green",
  //     car_model_year: 2006,
  //     car_vin: "JHMZF1D63ES995796",
  //     price: "$1506.90",
  //     availability: false,
  //   },
  //   {
  //     id: 28,
  //     car: "Lotus",
  //     car_model: "Esprit",
  //     car_color: "Purple",
  //     car_model_year: 1991,
  //     car_vin: "1G6DK8EY0B0373831",
  //     price: "$1061.74",
  //     availability: false,
  //   },
  //   {
  //     id: 29,
  //     car: "Mitsubishi",
  //     car_model: "Expo",
  //     car_color: "Maroon",
  //     car_model_year: 1995,
  //     car_vin: "WBAKA4C56CC120857",
  //     price: "$1828.44",
  //     availability: false,
  //   },
  //   {
  //     id: 30,
  //     car: "Land Rover",
  //     car_model: "Discovery Series II",
  //     car_color: "Orange",
  //     car_model_year: 2002,
  //     car_vin: "1D7RE3BK4AS603019",
  //     price: "$2911.93",
  //     availability: false,
  //   },
  //   {
  //     id: 31,
  //     car: "Geo",
  //     car_model: "Tracker",
  //     car_color: "Khaki",
  //     car_model_year: 1997,
  //     car_vin: "1D7CE3BK0AS555394",
  //     price: "$3894.12",
  //     availability: true,
  //   },
  //   {
  //     id: 32,
  //     car: "Mercury",
  //     car_model: "Monterey",
  //     car_color: "Violet",
  //     car_model_year: 2004,
  //     car_vin: "KMHD35LH2FU144301",
  //     price: "$2799.57",
  //     availability: true,
  //   },
  //   {
  //     id: 33,
  //     car: "BMW",
  //     car_model: "3 Series",
  //     car_color: "Violet",
  //     car_model_year: 1992,
  //     car_vin: "1G6KF57901U666328",
  //     price: "$1629.85",
  //     availability: false,
  //   },
  //   {
  //     id: 34,
  //     car: "GMC",
  //     car_model: "3500 Club Coupe",
  //     car_color: "Fuscia",
  //     car_model_year: 1998,
  //     car_vin: "WBAFR1C52BD688976",
  //     price: "$3559.47",
  //     availability: true,
  //   },
  //   {
  //     id: 35,
  //     car: "Volkswagen",
  //     car_model: "Passat",
  //     car_color: "Puce",
  //     car_model_year: 1998,
  //     car_vin: "JTDKN3DU1B0728650",
  //     price: "$1468.79",
  //     availability: true,
  //   },
  //   {
  //     id: 36,
  //     car: "GMC",
  //     car_model: "Yukon",
  //     car_color: "Indigo",
  //     car_model_year: 2007,
  //     car_vin: "WAUJT54B44N616083",
  //     price: "$2477.77",
  //     availability: false,
  //   },
  //   {
  //     id: 37,
  //     car: "Volkswagen",
  //     car_model: "Golf",
  //     car_color: "Khaki",
  //     car_model_year: 1991,
  //     car_vin: "1N4AL2AP1BN203395",
  //     price: "$3968.20",
  //     availability: false,
  //   },
  //   {
  //     id: 38,
  //     car: "Mercedes-Benz",
  //     car_model: "SLR McLaren",
  //     car_color: "Orange",
  //     car_model_year: 2008,
  //     car_vin: "WBAPK53549A473174",
  //     price: "$1437.86",
  //     availability: false,
  //   },
  //   {
  //     id: 39,
  //     car: "Land Rover",
  //     car_model: "Range Rover",
  //     car_color: "Khaki",
  //     car_model_year: 1993,
  //     car_vin: "1G6KF57925U041547",
  //     price: "$1341.78",
  //     availability: true,
  //   },
  //   {
  //     id: 40,
  //     car: "Lamborghini",
  //     car_model: "Countach",
  //     car_color: "Goldenrod",
  //     car_model_year: 1985,
  //     car_vin: "WA1AY74L08D036800",
  //     price: "$2139.19",
  //     availability: true,
  //   },
  //   {
  //     id: 41,
  //     car: "Dodge",
  //     car_model: "Durango",
  //     car_color: "Indigo",
  //     car_model_year: 2002,
  //     car_vin: "4A4AP3AU7FE541022",
  //     price: "$2887.16",
  //     availability: true,
  //   },
  //   {
  //     id: 42,
  //     car: "Saturn",
  //     car_model: "VUE",
  //     car_color: "Violet",
  //     car_model_year: 2006,
  //     car_vin: "1D7RB1CP5AS798832",
  //     price: "$3042.96",
  //     availability: true,
  //   },
  //   {
  //     id: 43,
  //     car: "Toyota",
  //     car_model: "Matrix",
  //     car_color: "Violet",
  //     car_model_year: 2005,
  //     car_vin: "1LNHL9DR9BG913773",
  //     price: "$1238.19",
  //     availability: false,
  //   },
  //   {
  //     id: 44,
  //     car: "Jaguar",
  //     car_model: "XJ",
  //     car_color: "Orange",
  //     car_model_year: 2006,
  //     car_vin: "WBALM5C52AE771888",
  //     price: "$3879.67",
  //     availability: true,
  //   },
  //   {
  //     id: 45,
  //     car: "Mercedes-Benz",
  //     car_model: "Sprinter 3500",
  //     car_color: "Maroon",
  //     car_model_year: 2011,
  //     car_vin: "2D4JN1AGXBR156369",
  //     price: "$3567.25",
  //     availability: true,
  //   },
  //   {
  //     id: 46,
  //     car: "Mitsubishi",
  //     car_model: "Montero",
  //     car_color: "Crimson",
  //     car_model_year: 1996,
  //     car_vin: "WAUGL68E25A756856",
  //     price: "$3217.31",
  //     availability: true,
  //   },
  //   {
  //     id: 47,
  //     car: "Subaru",
  //     car_model: "Impreza",
  //     car_color: "Fuscia",
  //     car_model_year: 2006,
  //     car_vin: "1N6AF0LY5EN597447",
  //     price: "$2437.81",
  //     availability: false,
  //   },
  //   {
  //     id: 48,
  //     car: "Audi",
  //     car_model: "A5",
  //     car_color: "Orange",
  //     car_model_year: 2012,
  //     car_vin: "WAUGFAFR1DA381976",
  //     price: "$2455.81",
  //     availability: false,
  //   },
  //   {
  //     id: 49,
  //     car: "Porsche",
  //     car_model: "928",
  //     car_color: "Blue",
  //     car_model_year: 1994,
  //     car_vin: "1GD312CG5CF627983",
  //     price: "$2112.12",
  //     availability: false,
  //   },
  //   {
  //     id: 50,
  //     car: "Acura",
  //     car_model: "TL",
  //     car_color: "Violet",
  //     car_model_year: 2000,
  //     car_vin: "3C63DPML9CG620139",
  //     price: "$3595.67",
  //     availability: false,
  //   },
  //   {
  //     id: 51,
  //     car: "Mitsubishi",
  //     car_model: "Mirage",
  //     car_color: "Teal",
  //     car_model_year: 1992,
  //     car_vin: "4T1BF1FK9EU758825",
  //     price: "$3642.50",
  //     availability: true,
  //   },
  //   {
  //     id: 52,
  //     car: "Kia",
  //     car_model: "Rondo",
  //     car_color: "Red",
  //     car_model_year: 2008,
  //     car_vin: "1FTFW1E87AF978553",
  //     price: "$1150.48",
  //     availability: true,
  //   },
  //   {
  //     id: 53,
  //     car: "Nissan",
  //     car_model: "Maxima",
  //     car_color: "Purple",
  //     car_model_year: 2005,
  //     car_vin: "WVWED7AJ4DW800765",
  //     price: "$2308.71",
  //     availability: true,
  //   },
  //   {
  //     id: 54,
  //     car: "Suzuki",
  //     car_model: "Samurai",
  //     car_color: "Fuscia",
  //     car_model_year: 1992,
  //     car_vin: "WVWEU9AN6AE112654",
  //     price: "$3523.87",
  //     availability: true,
  //   },
  //   {
  //     id: 55,
  //     car: "Chevrolet",
  //     car_model: "Cobalt",
  //     car_color: "Pink",
  //     car_model_year: 2009,
  //     car_vin: "3GYT4NEF2DG431298",
  //     price: "$1668.89",
  //     availability: true,
  //   },
  //   {
  //     id: 56,
  //     car: "GMC",
  //     car_model: "Acadia",
  //     car_color: "Pink",
  //     car_model_year: 2011,
  //     car_vin: "2HNYD28738H773678",
  //     price: "$3564.30",
  //     availability: true,
  //   },
  //   {
  //     id: 57,
  //     car: "Volkswagen",
  //     car_model: "Golf",
  //     car_color: "Maroon",
  //     car_model_year: 1998,
  //     car_vin: "WAULV44E47N641626",
  //     price: "$3866.51",
  //     availability: true,
  //   },
  //   {
  //     id: 58,
  //     car: "Lexus",
  //     car_model: "GS",
  //     car_color: "Violet",
  //     car_model_year: 1996,
  //     car_vin: "2G4WB55K111092037",
  //     price: "$3045.06",
  //     availability: true,
  //   },
  //   {
  //     id: 59,
  //     car: "Cadillac",
  //     car_model: "Eldorado",
  //     car_color: "Orange",
  //     car_model_year: 2002,
  //     car_vin: "3D7JB1EPXAG321542",
  //     price: "$1652.75",
  //     availability: true,
  //   },
  //   {
  //     id: 60,
  //     car: "Ford",
  //     car_model: "F250",
  //     car_color: "Teal",
  //     car_model_year: 2010,
  //     car_vin: "2FMDK3GC4AB714669",
  //     price: "$3702.14",
  //     availability: true,
  //   },
  //   {
  //     id: 61,
  //     car: "GMC",
  //     car_model: "Savana 2500",
  //     car_color: "Turquoise",
  //     car_model_year: 2005,
  //     car_vin: "WBAEK73495B976911",
  //     price: "$3330.66",
  //     availability: false,
  //   },
  //   {
  //     id: 62,
  //     car: "BMW",
  //     car_model: "645",
  //     car_color: "Blue",
  //     car_model_year: 2005,
  //     car_vin: "JN8AZ1MUXEW948606",
  //     price: "$1498.82",
  //     availability: true,
  //   },
  //   {
  //     id: 63,
  //     car: "Chevrolet",
  //     car_model: "1500",
  //     car_color: "Orange",
  //     car_model_year: 1994,
  //     car_vin: "5LMJJ2H51DE856700",
  //     price: "$2063.98",
  //     availability: false,
  //   },
  //   {
  //     id: 64,
  //     car: "Ford",
  //     car_model: "Taurus",
  //     car_color: "Khaki",
  //     car_model_year: 1992,
  //     car_vin: "JN8AZ2NC2F9884105",
  //     price: "$2802.49",
  //     availability: false,
  //   },
  //   {
  //     id: 65,
  //     car: "Lexus",
  //     car_model: "RX",
  //     car_color: "Maroon",
  //     car_model_year: 2007,
  //     car_vin: "WAUJFAFH1DN066052",
  //     price: "$2462.45",
  //     availability: false,
  //   },
  //   {
  //     id: 66,
  //     car: "GMC",
  //     car_model: "Savana",
  //     car_color: "Goldenrod",
  //     car_model_year: 2010,
  //     car_vin: "KMHHT6KD4CU061471",
  //     price: "$1315.98",
  //     availability: true,
  //   },
  //   {
  //     id: 67,
  //     car: "Kia",
  //     car_model: "Spectra",
  //     car_color: "Khaki",
  //     car_model_year: 2007,
  //     car_vin: "2G4WF551531515507",
  //     price: "$3011.10",
  //     availability: false,
  //   },
  //   {
  //     id: 68,
  //     car: "Bentley",
  //     car_model: "Continental GT",
  //     car_color: "Turquoise",
  //     car_model_year: 2012,
  //     car_vin: "3D4PG6FV3AT242143",
  //     price: "$1419.38",
  //     availability: false,
  //   },
  //   {
  //     id: 69,
  //     car: "Dodge",
  //     car_model: "Dakota",
  //     car_color: "Goldenrod",
  //     car_model_year: 2008,
  //     car_vin: "1G6DP577870103936",
  //     price: "$1407.10",
  //     availability: false,
  //   },
  //   {
  //     id: 70,
  //     car: "Honda",
  //     car_model: "Civic",
  //     car_color: "Turquoise",
  //     car_model_year: 2001,
  //     car_vin: "5N1AA0NC3DN401888",
  //     price: "$2508.52",
  //     availability: true,
  //   },
  //   {
  //     id: 71,
  //     car: "Lexus",
  //     car_model: "LS",
  //     car_color: "Violet",
  //     car_model_year: 1992,
  //     car_vin: "5NPDH4AE3DH626081",
  //     price: "$1700.50",
  //     availability: false,
  //   },
  //   {
  //     id: 72,
  //     car: "BMW",
  //     car_model: "1 Series",
  //     car_color: "Fuscia",
  //     car_model_year: 2012,
  //     car_vin: "KNDJN2A21F7706444",
  //     price: "$1231.67",
  //     availability: false,
  //   },
  //   {
  //     id: 73,
  //     car: "Ferrari",
  //     car_model: "F430",
  //     car_color: "Pink",
  //     car_model_year: 2007,
  //     car_vin: "WAUTFAFH1CN253945",
  //     price: "$1185.92",
  //     availability: false,
  //   },
  //   {
  //     id: 74,
  //     car: "Pontiac",
  //     car_model: "Grand Prix",
  //     car_color: "Violet",
  //     car_model_year: 1996,
  //     car_vin: "WAUMFBFL7DN961584",
  //     price: "$2065.93",
  //     availability: true,
  //   },
  //   {
  //     id: 75,
  //     car: "Suzuki",
  //     car_model: "Esteem",
  //     car_color: "Puce",
  //     car_model_year: 1995,
  //     car_vin: "WDDHF2EB6CA516312",
  //     price: "$2054.55",
  //     availability: true,
  //   },
  //   {
  //     id: 76,
  //     car: "Nissan",
  //     car_model: "Versa",
  //     car_color: "Crimson",
  //     car_model_year: 2012,
  //     car_vin: "WBABN73423P498440",
  //     price: "$1500.26",
  //     availability: false,
  //   },
  //   {
  //     id: 77,
  //     car: "Suzuki",
  //     car_model: "Swift",
  //     car_color: "Teal",
  //     car_model_year: 1995,
  //     car_vin: "1FMEU7DE4AU871463",
  //     price: "$3864.08",
  //     availability: true,
  //   },
  //   {
  //     id: 78,
  //     car: "Mitsubishi",
  //     car_model: "Diamante",
  //     car_color: "Turquoise",
  //     car_model_year: 2000,
  //     car_vin: "WAUDT48H26K307934",
  //     price: "$2886.85",
  //     availability: false,
  //   },
  //   {
  //     id: 79,
  //     car: "Cadillac",
  //     car_model: "XLR-V",
  //     car_color: "Goldenrod",
  //     car_model_year: 2007,
  //     car_vin: "WAUUL98E46A029305",
  //     price: "$1089.89",
  //     availability: false,
  //   },
  //   {
  //     id: 80,
  //     car: "Honda",
  //     car_model: "Pilot",
  //     car_color: "Green",
  //     car_model_year: 2009,
  //     car_vin: "KMHTC6AD9EU079642",
  //     price: "$1897.01",
  //     availability: false,
  //   },
  //   {
  //     id: 81,
  //     car: "Nissan",
  //     car_model: "Frontier",
  //     car_color: "Pink",
  //     car_model_year: 2011,
  //     car_vin: "5NPDH4AE3FH402697",
  //     price: "$1401.49",
  //     availability: false,
  //   },
  //   {
  //     id: 82,
  //     car: "Dodge",
  //     car_model: "Caravan",
  //     car_color: "Green",
  //     car_model_year: 2004,
  //     car_vin: "KNDPB3A20B7837660",
  //     price: "$1367.44",
  //     availability: true,
  //   },
  //   {
  //     id: 83,
  //     car: "Aston Martin",
  //     car_model: "DB9",
  //     car_color: "Mauv",
  //     car_model_year: 2006,
  //     car_vin: "1GKKRNED0DJ826326",
  //     price: "$3051.68",
  //     availability: false,
  //   },
  //   {
  //     id: 84,
  //     car: "Mercedes-Benz",
  //     car_model: "300E",
  //     car_color: "Blue",
  //     car_model_year: 1992,
  //     car_vin: "WBAEW53424P914812",
  //     price: "$1186.54",
  //     availability: true,
  //   },
  //   {
  //     id: 85,
  //     car: "Subaru",
  //     car_model: "SVX",
  //     car_color: "Blue",
  //     car_model_year: 1994,
  //     car_vin: "JHMZF1C44CS019846",
  //     price: "$1209.90",
  //     availability: true,
  //   },
  //   {
  //     id: 86,
  //     car: "Dodge",
  //     car_model: "Ram Van 2500",
  //     car_color: "Puce",
  //     car_model_year: 1997,
  //     car_vin: "JTDKDTB34F1336579",
  //     price: "$2986.94",
  //     availability: false,
  //   },
  //   {
  //     id: 87,
  //     car: "Chevrolet",
  //     car_model: "Corvette",
  //     car_color: "Turquoise",
  //     car_model_year: 1961,
  //     car_vin: "SCFAD22353K691631",
  //     price: "$3783.62",
  //     availability: true,
  //   },
  //   {
  //     id: 88,
  //     car: "Mitsubishi",
  //     car_model: "Diamante",
  //     car_color: "Indigo",
  //     car_model_year: 2000,
  //     car_vin: "1G6DL8E36D0269297",
  //     price: "$1312.27",
  //     availability: true,
  //   },
  //   {
  //     id: 89,
  //     car: "Mitsubishi",
  //     car_model: "Expo",
  //     car_color: "Maroon",
  //     car_model_year: 1994,
  //     car_vin: "WP0AA2A92FS592332",
  //     price: "$1946.73",
  //     availability: true,
  //   },
  //   {
  //     id: 90,
  //     car: "GMC",
  //     car_model: "Safari",
  //     car_color: "Goldenrod",
  //     car_model_year: 1998,
  //     car_vin: "WBAVB73517F584929",
  //     price: "$3748.78",
  //     availability: true,
  //   },
  //   {
  //     id: 91,
  //     car: "BMW",
  //     car_model: "M5",
  //     car_color: "Crimson",
  //     car_model_year: 2009,
  //     car_vin: "WVGAV7AX5FW407579",
  //     price: "$3914.79",
  //     availability: false,
  //   },
  //   {
  //     id: 92,
  //     car: "Dodge",
  //     car_model: "Ram 3500",
  //     car_color: "Pink",
  //     car_model_year: 1999,
  //     car_vin: "YV1612FH2E2873271",
  //     price: "$3001.79",
  //     availability: true,
  //   },
  //   {
  //     id: 93,
  //     car: "Chevrolet",
  //     car_model: "G-Series 1500",
  //     car_color: "Fuscia",
  //     car_model_year: 1998,
  //     car_vin: "1D7RB1GT1BS878251",
  //     price: "$3471.12",
  //     availability: false,
  //   },
  //   {
  //     id: 94,
  //     car: "Toyota",
  //     car_model: "Camry Hybrid",
  //     car_color: "Turquoise",
  //     car_model_year: 2007,
  //     car_vin: "YV4902BZ3B1046673",
  //     price: "$2195.59",
  //     availability: false,
  //   },
  //   {
  //     id: 95,
  //     car: "Ford",
  //     car_model: "Contour",
  //     car_color: "Orange",
  //     car_model_year: 1997,
  //     car_vin: "WAUHF98P88A144132",
  //     price: "$1981.14",
  //     availability: true,
  //   },
  //   {
  //     id: 96,
  //     car: "Mercedes-Benz",
  //     car_model: "SL-Class",
  //     car_color: "Khaki",
  //     car_model_year: 2006,
  //     car_vin: "YV1902AH3D1119632",
  //     price: "$1937.08",
  //     availability: false,
  //   },
  //   {
  //     id: 97,
  //     car: "Subaru",
  //     car_model: "Outback",
  //     car_color: "Puce",
  //     car_model_year: 2002,
  //     car_vin: "KMHFG4JG3FA418690",
  //     price: "$1934.78",
  //     availability: false,
  //   },
  //   {
  //     id: 98,
  //     car: "Ford",
  //     car_model: "E-Series",
  //     car_color: "Violet",
  //     car_model_year: 2003,
  //     car_vin: "1N6AD0CU7DN643894",
  //     price: "$3202.99",
  //     availability: true,
  //   },
  //   {
  //     id: 99,
  //     car: "Ford",
  //     car_model: "F150",
  //     car_color: "Pink",
  //     car_model_year: 1994,
  //     car_vin: "1FTEX1C81AK728857",
  //     price: "$1245.14",
  //     availability: true,
  //   },
  //   {
  //     id: 100,
  //     car: "Hyundai",
  //     car_model: "Veloster",
  //     car_color: "Indigo",
  //     car_model_year: 2012,
  //     car_vin: "KMHTC6AD4DU412781",
  //     price: "$2987.01",
  //     availability: true,
  //   },
];

export default data;
